# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := XWord puz yajl

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

XWord: puz
	@echo "==== Building XWord ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f XWord.make

puz: yajl
	@echo "==== Building puz ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f puz.make

yajl: 
	@echo "==== Building yajl ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f yajl.make

clean:
	@${MAKE} --no-print-directory -C . -f XWord.make clean
	@${MAKE} --no-print-directory -C . -f puz.make clean
	@${MAKE} --no-print-directory -C . -f yajl.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo "   debug32"
	@echo "   release32"
	@echo "   debug64"
	@echo "   release64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   XWord"
	@echo "   puz"
	@echo "   yajl"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
